name: Build Fruitties sample

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'Fruitties/**'
      - '.github/workflows/Fruitties.yml'
  pull_request:
    paths:
      - 'Fruitties/**'
      - '.github/workflows/Fruitties.yml'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  SAMPLE_PATH: Fruitties

jobs:
  build_android:
    name: Build Android app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.SAMPLE_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Run Spotless check
        run: ./gradlew spotlessCheck --stacktrace

      - name: Build app
        run: ./gradlew assembleDebug lintDebug --stacktrace

  build_ios:
    name: Build iOS app
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ${{ env.SAMPLE_PATH }}

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
    
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build iOS app
        uses: mxcl/xcodebuild@v3
        with:
          xcode: ^16
          scheme: iosApp
          platform: iOS
          action: build
          working-directory: ${{ env.SAMPLE_PATH }}/iosApp